# ref https://ctan.org/tex-archive/info/typstfun

[math_commands]
arccos = "arccos"
arcsin = "arcsin"
arctan = "arctan"
arg = "arg"
bar = "macron"
binom = "binom"
boldsymbol = "bold"
cos = "cos"
cosh = "cosh"
cot = "cot"
coth = "coth"
csc = "csc"
dbinom = "binom"
ddot = "dot.double" # 'dot.double' or 'diaer'
deg = "deg"
det = "det"
dfrac = "frac"
dim = "dim"
dot = "dot"
exp = "exp"
frac = "frac"
gcd = "gcd"
hat = "hat"
# hspace = "h"
inf = "inf"
ker = "ker"
# left = "lr"
lg = "lg"
lim = "lim"
liminf = "liminf"
limsup = "limsup"
ln = "ln"
log = "log"
mathbb = "bb"
mathcal = "cal"
mathsf = "sans"
mathtt = "mono"
max = "max"
min = "min"
mod = "mod"
overbrace = "overbrace"
overline = "overline"
qquad = "wide"
quad = "quad"
# right = "lr"
sec = "sec"
sin = "sin"
sinh = "sinh"
sqrt = "sqrt" # 'sqrt' or 'root'
sup = "sup"
tan = "tan"
tanh = "tanh"
tbinom = "binom"
tfrac = "frac"
tilde = "tilde"
underbrace = "underbrace"
vec = "arrow"
widehat = "hat"

[math_symbols]
Cap = "sect.double"
Cup = "union.double"
Delta = "Delta"
Gamma = "Gamma"
Join = "join"
Lambda = "Lambda"
Longrightarrow = "arrow.r.double.long"
Omega = "Omega"
Phi = "Phi"
Pi = "Pi"
Psi = "Psi"
Rightarrow = "arrow.double"
Sigma = "Sigma"
Theta = "Theta"
aleph = "alef"
alpha = "alpha"
# amalg = "product.co"
angle = "angle"
approx = "approx"
approxeq = "approx.eq"
ast = "ast"
beta = "beta"
bigcap = "sect.big"
bigcirc = "circle.big"
bigcup = "union.big"
bigodot = "dot.circle.big"
bigoplus = "xor.big" # or "plus.circle.big"
bigotimes = "times.circle.big"
bigsqcup = "union.sq.big"
bigtriangledown = "triangle.b"
bigtriangleup = "triangle.t"
biguplus = "union.plus.big"
bigvee = "or.big"
bigwedge = "and.big"
# bowtie = "join"
bullet = "bullet"
cap = "sect"
cdot = "dot.op" # 'dot.op' or 'dot.c'
cdots = "dots.c"
checkmark = "checkmark"
chi = "chi"
circ = "circle.small" # 'circle.small' or 'compose'
colon = "colon"
cong = "tilde.equiv"
coprod = "product.co"
cup = "union"
curlyvee = "or.curly"
curlywedge = "and.curly"
dagger = "dagger"
dashv = "tack.l"
ddagger = "dagger.double"
delta = "delta"
ddots = "dots.down"
diamond = "diamond"
div = "div"
divideontimes = "times.div"
dotplus = "plus.dot"
downarrow = "arrow.b"
ell = "ell"
emptyset = "nothing"
epsilon = "epsilon.alt"
equiv = "equiv"
eta = "eta"
exists = "exists"
forall = "forall"
# frown = "paren.t"
gamma = "gamma"
ge = "gt.eq"
geq = "gt.eq"
geqslant = "gt.eq.slant"
gg = "gt.double"
hbar = "planck.reduce"
imath = "dotless.i"
iiiint = "intgral.quad"
iiint = "integral.triple"
iint = "integral.double"
in = "in"
infty = "infinity"
int = "integral"
intercal = "top" # 'top' or 'tack.b'
iota = "iota"
jmath = "dotless.j"
kappa = "kappa"
lambda = "lambda"
land = "and"
langle = "angle.l"
lbrace = "brace.l"
lbrack = "bracket.l"
ldots = "dots.l"
le = "lt.eq"
leadsto = "arrow.squiggly"
leftarrow = "arrow.l"
leftthreetimes = "times.three.l"
leftrightarrow = "arrow.l.r"
leq = "lt.eq"
leqslant = "lt.eq.slant"
lhd = "triangle.l"
ll = "lt.double"
longmapsto = "arrow.long.bar"
longrightarrow = "arrow.long"
ltimes = "times.l"
mapsto = "arrow.bar"
measuredangle = "angle.arc"
mid = "divides"
models = "models"
mp = "minus.plus"
mu = "mu"
nRightarrow = "arrow.double.not"
nabla = "nabla"
# natural = # Typst does not have a symbol for this
ncong = "tilde.nequiv"
ne = "eq.not"
neg = "not"
neq = "eq.not"
nexists = "exists.not"
ngeq = "gt.eq.not"
ni = "in.rev"
nleftarrow = "arrow.l.not"
nleq = "lt.eq.not"
nparallel = "parallel.not"
nmid = "divides.not"
notin = "in.not"
nrightarrow = "arrow.not"
nsim = "tilde.not"
nsubseteq = "subset.eq.not"
nu = "nu"
ntriangleleft = "lt.tri.not"
ntriangleright = "gt.tri.not"
nwarrow = "arrow.tl"
odot = "dot.circle"
oint = "integral.cont"
omega = "omega"
# omicron = "omicron"
ominus = "minus.circle"
oplus = "xor" # or "plus.circle"
# oslash = # Unfortunately Typst does not have a symbol for this
otimes = "times.circle"
parallel = "parallel"
partial = "diff"
perp = "perp"
phi = "phi.alt"
pi = "pi"
pm = "plus.minus"
pounds = "pound"
prec = "prec"
preceq = "prec.eq"
prime = "prime"
prod = "product"
propto = "prop"
psi = "psi"
rangle = "angle.r"
rbrace = "brace.r"
rbrack = "bracket.r"
# rceil = "ceil.r" # Unfortunately Typst does not have a symbol for this
# rfloor = "floor.r" # Unfortunately Typst does not have a symbol for this
rhd = "triangle"
rho = "rho"
rightarrow = "arrow.r"
rightthreetimes = "times.three.r"
rtimes = "times.r"
setminus = "without" # Not exactly. Ideally this should be something like "withoug.big"
sigma = "sigma"
sim = "tilde"
simeq = "tilde.eq"
slash =  "slash" # or "\\/" # This symbol is not supported by Typst but supported by LaTeX
smallsetminus = "without"
# smile = "paren.b"  # Typst does not have a symbol for this. "paren.b" just look like it but has different size.
spadesuit = "suit.spade"
sqcap = "sect.sq"
sqcup = "union.sq"
sqsubseteq = "subset.eq.sq"
sqsupseteq = "supset.eq.sq"
star = "star"
subset = "subset"
subseteq = "subset.eq"
subsetneq = "subset.neq"
succ = "succ"
succeq = "succ.eq"
sum = "sum"
supset = "supset"
supseteq = "supset.eq"
supsetneq = "supset.neq"
# surd = # not supported by Typst
swarrow = "arrow.bl"
tau = "tau"
theta = "theta"
times = "times"
to = "arrow.r"
top = "top"
triangle = "triangle.t"
triangledown = "triangle.b.small"
triangleleft = "triangle.l.small"
triangleright = "triangle.r.small"
twoheadrightarrow = "arrow.r.twohead"
uparrow = "arrow.t"
updownarrow = "arrow.t.b"
upharpoonright = "harpoon.tr"
uplus = "union.plus"
upsilon = "upsilon"
varepsilon = "epsilon"
varphi = "phi"
varpi = "pi.alt"
varrho = "rho.alt"
varsigma = "sigma.alt"
vartheta = "theta.alt"
vdash = "tack.r"
vdots = "dots.v"
vee = "or"
wedge = "and"
# wp = # not supported by Typst
wr = "wreath"
xi = "xi"
yen = "yen"
zeta = "zeta"
